version = "2"

[workspace]

[package]
path = "github.com/diodeinc/pcb/test-workspaces/packaging-v2"
pcb-version = "0.2"

[dependencies]
"github.com/akhilles/stdlib" = "0.4.4"

[assets]
"gitlab.com/kicad/libraries/kicad-symbols" = "9.0.3"
"gitlab.com/kicad/libraries/kicad-footprints" = "9.0.3"

[access]
allow = ["*"]
