[workspace]
name = "examples"
pcb-version = "0.3"
members = [
    "components/*",
    "reference/*",
    "modules/*",
    "boards/*",
    "graphics/*",
]

[dependencies]
"gitlab.com/kicad/libraries/kicad-symbols" = "9.0.3"
