[workspace]
name = "examples"
pcb-version = "0.3"
members = [
    "components/*",
    "reference/*",
    "modules/*",
    "boards/*",
    "graphics/*",
]

[assets]
"gitlab.com/kicad/libraries/kicad-footprints/Package_DFN_QFN.pretty/DFN-10-1EP_3x3mm_P0.5mm_EP1.55x2.48mm.kicad_mod" = "9.0.3"
"gitlab.com/kicad/libraries/kicad-symbols/Amplifier_Current.kicad_sym" = "9.0.3"
"gitlab.com/kicad/libraries/kicad-symbols/Analog_ADC.kicad_sym" = "9.0.3"
"gitlab.com/kicad/libraries/kicad-symbols/power.kicad_sym" = "9.0.3"
