version = "2"

[package]
pcb-version = "0.2"

[board]
name = "DM0002"
description = "Diode Probe (RP2040 CMSIS-DAP)"

[dependencies]
"github.com/akhilles/stdlib" = "0.4.4"
"github.com/diodeinc/pcb/test-workspaces/packaging-v2" = "0.1"

[assets]
"gitlab.com/kicad/libraries/kicad-symbols" = "9.0.3"
"gitlab.com/kicad/libraries/kicad-footprints" = "9.0.3"
