version = "2"

[package]
pcb-version = "0.2"

[board]
name = "DM0002"
description = "Diode Probe (RP2040 CMSIS-DAP)"

[dependencies]
"github.com/akhilles/stdlib" = { workspace = true }
"github.com/diodeinc/pcb/test-workspaces/packaging-v2" = { path = "../.." }
